version: 0.2

phases:
  install:
    commands:
      #- rm package-lock.json
      - printenv
      - ls -R
      - pip install -r requirements.txt -t "$PWD"
      
  build:
    commands:
      ## Integration test environment
      #- serverless deploy --stage test -v
      - python -m unittest test_module.py

  post_build:
    commands:
      ## Remove integration testing environment
      #- serverless remove --stage test -v

artifacts:
 files:
   - test.jason
